services:
  audio_to_text:
    build:
      context: ../..
      dockerfile: docker/audio_to_text/Dockerfile.dev
    env_file:
      - ../../.env.audio_to_text
    ports:
      - "7865:7865"
    volumes:
      - ../../:/app
      - audio_to_text_cache:/opt/hf-cache
    command: ["--ui", "--ui-host", "0.0.0.0", "--ui-port", "7865"]

volumes:
  audio_to_text_cache:
