services:
  audio_to_text_ui:
    build:
      context: ../..
      dockerfile: docker/audio_to_text_ui/Dockerfile.dev
    env_file:
      - ../../.env.audio_to_text_ui
    ports:
      - "7860:7860"
    volumes:
      - ../../audio_to_text_ui:/app/audio_to_text_ui
    depends_on:
      - audio_to_text_backend

  audio_to_text_backend:
    build:
      context: ../..
      dockerfile: docker/audio_to_text_backend/Dockerfile.dev
    env_file:
      - ../../.env.audio_to_text_backend
    ports:
      - "8080:8080"
    volumes:
      - ../../:/app
      - ../../data:/app/data
    command: ["--host", "0.0.0.0", "--port", "8080"]
    depends_on:
      - audio_to_text_grpc

  audio_to_text_grpc:
    build:
      context: ../..
      dockerfile: docker/audio_to_text_grpc/Dockerfile.dev
    env_file:
      - ../../.env.audio_to_text_grpc
    ports:
      - "50051:50051"
    volumes:
      - ../../:/app
      - ../../data:/app/data
      - ../../data/hf-cache:/opt/hf-cache
      - ../../data/torch-cache:/opt/torch-cache
    command: ["--host", "0.0.0.0", "--port", "50051"]
